# Datasource padrão SQLite
quarkus.datasource.db-kind=sqlite
quarkus.datasource.jdbc.url=jdbc:sqlite:simulaicaixa.db
quarkus.datasource.jdbc.max-size=8
quarkus.datasource.jdbc.min-size=1

# Hibernate ORM JPA
quarkus.hibernate-orm.database.generation=update
#quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.format-sql=true

# JWT/Segurança
mp.jwt.verify.issuer=simulaicaixa
smallrye.jwt.verify.algorithm=HS256
smallrye.jwt.sign.key=chave-super-secreta-simulaicaixa
smallrye.jwt.verify.key=chave-super-secreta-simulaicaixa
smallrye.jwt.token.header=Authorization
smallrye.jwt.token.scheme=Bearer
